leftnav:
- identifier: f63f90d3-613f-5724-31d2-654fe7fd5aa1
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: c06ce4b4-36ff-517c-893c-8710040a36af
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: 4d0ce37c-ed81-5be3-8ee0-041c5faeb2bf
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: 4002e54e-c95d-3246-5fdc-faaaf30cdfaf
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
